name: Go Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Set up Go
        uses: actions/setup-go@v5.0.2
        with:
          # Path to the go.mod or go.work file.
          go-version-file: ./backend/go.mod
          # Set this option to true if you want the action to always check for the latest available version that satisfies the version spec
          check-latest: true
      
      - name: Build
        run: go build ./backend/.
          
